---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: opentelemetry-demo-productcatalogservice
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: opentelemetry-demo-productcatalogservice
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
...